version: '3'

services:
  app:
    image: nginx:latest
    restart: always
    ports:
      - 38908:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - php
  php:
    image: php:8-apache
    restart: always
    volumes:
      - ./src:/var/www/html:ro
    networks:
      - internal
  bot:
    build: bot
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://app/
      APPURLREGEX: ^.*$
      APPFLAG: TCF2023{1642071c-ebb8-4b3f-91fa-56abf92cf64c}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
