version: "3.9"

services:
  jail:
    build: .
    userns_mode: host
    volumes:
      - ./app.py:/srv/app/run:ro
      - ./flag.txt:/srv/flag.txt:ro
    ports:
      - 25776:5000
    restart: always
    privileged: true
